---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_vpc_net_info

  post_tasks:
    - name: Ensure ec2 vpc net info is verified
      tags:
        - ec2_vpc_net_info
      ansible.builtin.assert:
        that:
          - _ec2_vpc_net_info_dict['linuxhq-00'].id is defined
          - _ec2_vpc_net_info_dict['linuxhq-01'].id is defined
          - _ec2_vpc_net_info_dict['linuxhq-02'].id is defined
          - _ec2_vpc_net_info_dict['linuxhq-03'].id is defined
          - _ec2_vpc_net_info_dict['linuxhq-04'].id is defined

    - name: Ensure inventory lists are formatted
      tags:
        - ec2_vpc_net
      ansible.builtin.set_fact:
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      tags:
        - ec2_vpc_net_info
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_vpc_net
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
