---
dependencies:
  - role: linuxhq.aws.ec2_vpc_prefix_list_info
    tags: ec2_security_group
  - role: linuxhq.aws.ec2_vpc_net_info
    tags: ec2_security_group
galaxy_info:
  role_name: ec2_security_group
  author: Taylor Kimball
  description: Manage aws ec2 security groups
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - ec2
    - group
    - security
...
