---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        ec2_vpc_net_list:
          - name: linuxhq
            cidr_block: 10.0.0.0/16

        ec2_security_group_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['linuxhq'].id }}"
            security_groups:
              - name: linuxhq-ftp
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 21
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-ssh
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 22
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-telnet
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 23
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-smtp
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 25
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-domain
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 53
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-http
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 80
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-pop3
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 110
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-imap
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 143
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-ldap
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 389
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-https
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 443
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-ircd
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 6667
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1
              - name: linuxhq-ircs
                rules:
                  - cidr_ip: "{{ ec2_vpc_net_list.0.cidr_block }}"
                    ports:
                      - 6697
                    proto: tcp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
