---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_security_group_info
    - ec2_vpc_net_info

  post_tasks:
    - name: Ensure info is verified
      tags:
        - ec2_security_group_info
      ansible.builtin.assert:
        that:
          - _ec2_security_group_info_dict['linuxhq-ftp'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-ssh'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-telnet'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-smtp'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-domain'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-http'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-pop3'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-imap'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-ldap'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-https'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-ircd'].group_id is defined
          - _ec2_security_group_info_dict['linuxhq-ircs'].group_id is defined

    - name: Ensure inventory lists are formatted
      tags:
        - ec2_security_group_info
      ansible.builtin.set_fact:
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_security_group_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['linuxhq'].id }}"
            security_groups:
              "{{ ec2_security_group_list.0.security_groups |
                  map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      tags:
        - ec2_security_group_info
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_security_group
        - ec2_vpc_net
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
