---
dependencies:
  - role: ec2_vpc_net_info
    tags: route53_zone_associate
  - role: route53_info
    tags: route53_zone_associate
galaxy_info:
  role_name: route53_zone_associate
  author: Taylor Kimball
  description: Manage aws route53 private zone virtual private cloud associations
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - associate
    - aws
    - route53
    - zone
...
