---
allow_duplicates: true
dependencies: []
galaxy_info:
  role_name: ec2_vol_info
  author: Taylor Kimball
  description: Gather information about aws ec2 volumes
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - ec2
    - info
    - volume
...
