---
dependencies:
  - role: kms_key_info
    tags: cloudwatchlogs_log_group
galaxy_info:
  role_name: cloudwatchlogs_log_group
  author: Taylor Kimball
  description: Manage aws cloudwatchlogs log groups
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - cloudwatch
    - group
    - log
...
