---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_vpc_prefix_list_info

  post_tasks:
    - name: Ensure ec2 vpc prefix list info is verified
      tags:
        - ec2_vpc_prefix_list_info
      ansible.builtin.assert:
        that:
          - _ec2_vpc_prefix_list_info_dict['linuxhq-localhost'].PrefixListId is defined
          - _ec2_vpc_prefix_list_info_dict['linuxhq-localhost'].PrefixListName == 'linuxhq-localhost'
          - _ec2_vpc_prefix_list_info_dict['linuxhq-private'].PrefixListId is defined
          - _ec2_vpc_prefix_list_info_dict['linuxhq-private'].PrefixListName == 'linuxhq-private'

    - name: Ensure inventory lists are formatted
      tags:
        - ec2_vpc_prefix_list_info
      ansible.builtin.set_fact:
        ec2_vpc_prefix_list_entries:
          "{{ ec2_vpc_prefix_list_entries |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      tags:
        - ec2_vpc_prefix_list_info
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_vpc_prefix_list
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
