---
dependencies:
  - role: ec2_vpc_net_info
    tags: efs
  - role: ec2_vpc_subnet_info
    tags: efs
galaxy_info:
  role_name: efs
  author: Taylor Kimball
  description: Manage aws elastic filesystems
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - efs
...
