---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_vpc_net_info
    - ec2_vpc_igw_info

  post_tasks:
    - name: Ensure ec2 vpc igw info is verified
      tags:
        - ec2_vpc_igw_info
      ansible.builtin.assert:
        that:
          - _ec2_vpc_igw_info_dict['linuxhq'].attachments is defined
          - _ec2_vpc_igw_info_dict['linuxhq'].attachments.0.state == 'available'
          - _ec2_vpc_igw_info_dict['linuxhq'].attachments.0.vpc_id == _ec2_vpc_net_info_dict['linuxhq'].id
          - _ec2_vpc_igw_info_dict['linuxhq'].internet_gateway_id is defined

    - name: Ensure inventory lists are formatted
      tags:
        - ec2_vpc_igw_info
      ansible.builtin.set_fact:
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_igw_list:
          "{{ ec2_vpc_igw_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      tags:
        - ec2_vpc_igw_info
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_vpc_igw
        - ec2_vpc_net
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
