---
dependencies:
  - role: ec2_vpc_net_info
    tags: route53_resolver_rule_associate
  - role: route53_resolver_rule_info
    tags: route53_resolver_rule_associate
galaxy_info:
  role_name: route53_resolver_rule_associate
  author: Taylor Kimball
  description: Manage aws route53 resolver rule associations
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - associate
    - amazon
    - aws
    - resolver
    - route53
    - rule
...
