---
dependencies:
  - role: linuxhq.aws.ec2_transit_gateway_info
    tags: ec2_transit_gateway_vpc_attachment
  - role: linuxhq.aws.ec2_vpc_subnet_info
    tags: ec2_transit_gateway_vpc_attachment
galaxy_info:
  role_name: ec2_transit_gateway_vpc_attachment
  author: Taylor Kimball
  description: Manage aws ec2 transit gateway vpc attachments
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - attachment
    - aws
    - ec2
    - gateway
    - transit
    - vpc
...
