---
dependencies: []
galaxy_info:
  role_name: wafv2_ip_set
  author: Taylor Kimball
  description: Manage aws wafv2 ip sets
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - ip
    - set
    - wafv2
...
