---
dependencies:
  - role: ec2_vpc_net_info
    tags: ec2_vpc_dhcp_option
galaxy_info:
  role_name: ec2_vpc_dhcp_option
  author: Taylor Kimball
  description: Manage aws virtual private cloud dhcp options
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - dhcp
    - ec2
    - option
    - vpc
...
