---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_eip_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _ec2_eip_info_dict['linuxhq-eip-01'].public_ip is defined
          - _ec2_eip_info_dict['linuxhq-eip-02'].public_ip is defined
          - _ec2_eip_info_dict['linuxhq-eip-03'].public_ip is defined
          - _ec2_eip_info_dict['linuxhq-eip-04'].public_ip is defined
          - _ec2_eip_info_dict['linuxhq-eip-05'].public_ip is defined

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ec2_eip_list:
          "{{ ec2_eip_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_eip
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
