---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: iam_account_alias
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - iam_account_alias_info
...
