---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - iam_account_alias_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _iam_account_alias_info_list.0 == iam_account_alias_name

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        iam_account_alias_state: absent

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - iam_account_alias
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
