---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        ec2_ami_info_list:
          - name: 'AlmaLinux OS 9'
            filters:
              owner-alias: aws-marketplace
              product-code: 3kukoxmnoighcsbjd0u4nq9ds
              product-code.type: marketplace
              is-public: true
              virtualization-type: hvm

        ec2_instance_list:
          - name: molecule-1
            exact_count: 1
            image_id: "{{ _ec2_ami_info_latest['AlmaLinux OS 9'] }}"
            instance_type: t2.medium
            vpc_subnet_id: "{{ _ec2_vpc_subnet_info_dict['molecule-a'].id }}"
          - name: molecule-2
            exact_count: 1
            image_id: "{{ _ec2_ami_info_latest['AlmaLinux OS 9'] }}"
            instance_type: t2.medium
            vpc_subnet_id: "{{ _ec2_vpc_subnet_info_dict['molecule-a'].id }}"
          - name: molecule-3
            exact_count: 1
            image_id: "{{ _ec2_ami_info_latest['AlmaLinux OS 9'] }}"
            instance_type: t2.medium
            vpc_subnet_id: "{{ _ec2_vpc_subnet_info_dict['molecule-a'].id }}"

        elb_target_group_list:
          - name: molecule-http-8080
            health_check_interval: 10
            health_check_path: /healthcheck
            health_check_port: 8080
            health_check_protocol: http
            healthy_threshold_count: 3
            port: 8080
            protocol: http
            stickiness_enabled: true
            target_type: instance
            targets:
              - Id: "{{ _ec2_instance_info_dict['molecule-1'].instance_id }}"
                Port: 8080
              - Id: "{{ _ec2_instance_info_dict['molecule-2'].instance_id }}"
                Port: 8080
              - Id: "{{ _ec2_instance_info_dict['molecule-3'].instance_id }}"
                Port: 8080
            unhealthy_threshold_count: 3
            vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"

          - name: molecule-http-8081
            health_check_interval: 10
            health_check_path: /admin
            health_check_port: 8081
            health_check_protocol: http
            healthy_threshold_count: 3
            port: 8081
            protocol: http
            stickiness_enabled: true
            target_type: instance
            targets:
              - Id: "{{ _ec2_instance_info_dict['molecule-1'].instance_id }}"
                Port: 8081
              - Id: "{{ _ec2_instance_info_dict['molecule-2'].instance_id }}"
                Port: 8081
              - Id: "{{ _ec2_instance_info_dict['molecule-3'].instance_id }}"
                Port: 8081
            unhealthy_threshold_count: 3
            vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"

        ec2_vpc_net_list:
          - name: molecule
            cidr_block: 192.168.0.0/24

        ec2_vpc_subnet_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"
            subnets:
              - name: molecule-a
                az: us-east-1a
                cidr: 192.168.0.0/24

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
