---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: iam_account_alias
      iam_account_alias_name: null
      tags:
        - molecule-idempotence-notest

    - iam_account_alias
...
