---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        ec2_placement_group_list:
          - strategy: cluster
            placement_groups:
              - name: linuxhq-cluster-1
              - name: linuxhq-cluster-2
              - name: linuxhq-cluster-3
              - name: linuxhq-cluster-4
              - name: linuxhq-cluster-5
              - name: linuxhq-cluster-6

          - strategy: partition
            placement_groups:
              - name: linuxhq-partition-1
                partition_count: 3
              - name: linuxhq-partition-2
                partition_count: 3
              - name: linuxhq-partition-3
                partition_count: 3
              - name: linuxhq-partition-4
                partition_count: 5
              - name: linuxhq-partition-5
                partition_count: 5
              - name: linuxhq-partition-6
                partition_count: 5
              - name: linuxhq-partition-7
                partition_count: 7
              - name: linuxhq-partition-8
                partition_count: 7
              - name: linuxhq-partition-9
                partition_count: 7

          - strategy: spread
            placement_groups:
              - name: linuxhq-spread-1
              - name: linuxhq-spread-2
              - name: linuxhq-spread-3
              - name: linuxhq-spread-4
              - name: linuxhq-spread-5
              - name: linuxhq-spread-6

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
