---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: ec2_instance_metadata
      ec2_instance_metadata_regions:
        - us-east-1
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - ec2_instance_metadata
...
