---
dependencies:
  - role: ec2_vpc_net_info
    tags: ec2_vpc_igw
galaxy_info:
  role_name: ec2_vpc_igw
  author: Taylor Kimball
  description: Manage aws virtual private cloud internet gateways
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - ec2
    - igw
    - vpc
...
