---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: ec2_vpc_prefix_list
      ec2_vpc_prefix_list_entries: []
      tags:
        - molecule-idempotence-notest

    - role: ec2_vpc_prefix_list
      ec2_vpc_prefix_list_entries:
        - name: linuxhq-localhost
          entries:
            - Cidr: 127.0.0.6/32
            - Cidr: 127.0.0.7/32
            - Cidr: 127.0.0.8/32
            - Cidr: 127.0.0.9/32
        - name: linuxhq-private
          entries:
            - Cidr: 192.168.6.0/24
            - Cidr: 192.168.7.0/24
            - Cidr: 192.168.8.0/24
            - Cidr: 192.168.9.0/24
      tags:
        - molecule-idempotence-notest

    - ec2_vpc_prefix_list
...
