---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    - name: Ensure inventory lists are formatted
      tags:
        - ec2_vpc_dhcp_option
      ansible.builtin.set_fact:
        ec2_vpc_dhcp_option_list:
          "{{ ec2_vpc_dhcp_option_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - ec2_vpc_dhcp_option
...
