---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: ec2_vpc_net
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_vpc_subnet
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_instance
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_vol
      ec2_vol_list: []
      tags:
        - molecule-idempotence-notest

    - ec2_vol
...
