---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        ec2_ami_info_list:
          - name: 'AlmaLinux OS 9'
            filters:
              owner-alias: aws-marketplace
              product-code: 3kukoxmnoighcsbjd0u4nq9ds
              product-code.type: marketplace
              is-public: true
              virtualization-type: hvm

        ec2_instance_info_filters:
          instance-state-name:
            - running

        ec2_instance_list:
          - name: linuxhq-a
            exact_count: 1
            image_id: "{{ _ec2_ami_info_latest['AlmaLinux OS 9'] }}"
            instance_type: t2.medium
            vpc_subnet_id: "{{ _ec2_vpc_subnet_info_dict['linuxhq-a'].id }}"
          - name: linuxhq-b
            exact_count: 1
            image_id: "{{ _ec2_ami_info_latest['AlmaLinux OS 9'] }}"
            instance_type: t2.medium
            vpc_subnet_id: "{{ _ec2_vpc_subnet_info_dict['linuxhq-b'].id }}"

        ec2_vol_list:
          - instance: "{{ _ec2_instance_info_dict['linuxhq-a'].instance_id }}"
            volumes:
              - name: linuxhq-vol-a-01
                device_name: sdf
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-a-02
                device_name: sdg
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-a-03
                device_name: sdh
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-a-04
                device_name: sdi
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-a-05
                device_name: sdj
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-a-06
                device_name: sdk
                volume_size: "{{ 10 | random(start=1) }}"

          - instance: "{{ _ec2_instance_info_dict['linuxhq-b'].instance_id }}"
            volumes:
              - name: linuxhq-vol-b-01
                device_name: sdf
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-b-02
                device_name: sdg
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-b-03
                device_name: sdh
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-b-04
                device_name: sdi
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-b-05
                device_name: sdj
                volume_size: "{{ 10 | random(start=1) }}"
              - name: linuxhq-vol-b-06
                device_name: sdk
                volume_size: "{{ 10 | random(start=1) }}"

        ec2_vpc_net_list:
          - name: linuxhq
            cidr_block: 10.0.0.0/16

        ec2_vpc_subnet_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['linuxhq'].id }}"
            subnets:
              - name: linuxhq-a
                az: us-east-1a
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(17,0) }}"
              - name: linuxhq-b
                az: us-east-1b
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(17,1) }}"

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
