---
dependencies: []
galaxy_info:
  role_name: s3_bucket
  author: Taylor Kimball
  description: Manage aws simple storage service buckets
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - bucket
    - s3
...
