---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        ec2_vpc_net_list:
          - name: molecule
            cidr_block: 10.0.0.0/16

        ec2_vpc_subnet_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"
            subnets:
              - name: molecule-a
                az: us-east-1a
                cidr: "{{ ec2_vpc_net_list.0.cidr_block | ansible.utils.ipsubnet(24,0) }}"
              - name: molecule-c
                az: us-east-1c
                cidr: "{{ ec2_vpc_net_list.0.cidr_block | ansible.utils.ipsubnet(24,1) }}"
              - name: molecule-d
                az: us-east-1d
                cidr: "{{ ec2_vpc_net_list.0.cidr_block | ansible.utils.ipsubnet(24,2) }}"

        eks_cluster_list:
          - name: molecule-eks1
            subnets:
              - "{{ _ec2_vpc_subnet_info_dict['molecule-a'].id }}"
              - "{{ _ec2_vpc_subnet_info_dict['molecule-c'].id }}"
              - "{{ _ec2_vpc_subnet_info_dict['molecule-d'].id }}"
            version: 1.34
            vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"

          - name: molecule-eks2
            iam_managed_policies:
              - AmazonEKSClusterPolicy
              - AmazonS3FullAccess
            iam_role_name: MoleculeEksClusterRole
            rules:
              - cidr_ip: 10.0.0.0/8
                ports:
                  - 443
                proto: tcp
            rules_egress:
              - cidr_ip: 10.0.0.0/8
                ports:
                  - 0-65535
                proto: tcp
            subnets:
              - "{{ _ec2_vpc_subnet_info_dict['molecule-a'].id }}"
              - "{{ _ec2_vpc_subnet_info_dict['molecule-c'].id }}"
              - "{{ _ec2_vpc_subnet_info_dict['molecule-d'].id }}"
            version: 1.35
            vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
