---
dependencies:
  - role: ec2_vpc_net_info
    tags: ssm_parameter
  - role: ec2_vpc_subnet_info
    tags: ssm_parameter
  - role: ec2_vpc_igw_info
    tags: ssm_parameter
  - role: ec2_vpc_nat_gateway_info
    tags: ssm_parameter
  - role: ec2_vpc_route_table_info
    tags: ssm_parameter
  - role: ec2_vpc_prefix_list_info
    tags: ssm_parameter
galaxy_info:
  role_name: ssm_parameter
  author: Taylor Kimball
  description: Manage aws systems manager key-value pairs
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - parameter
    - ssm
...
