---
dependencies: []
galaxy_info:
  role_name: ec2_vpc_prefix_list
  author: Taylor Kimball
  description: Manage aws virtual private cloud prefix lists
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - ec2
    - list
    - prefix
    - vpc
...
