---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        ec2_vpc_net_list:
          - name: linuxhq
            cidr_block: 10.0.0.0/16

        ec2_vpc_subnet_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['linuxhq'].id }}"
            subnets:
              - name: linuxhq-a-00
                az: us-east-1a
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,0) }}"
              - name: linuxhq-a-01
                az: us-east-1a
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,1) }}"
              - name: linuxhq-a-02
                az: us-east-1a
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,2) }}"
              - name: linuxhq-a-03
                az: us-east-1a
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,3) }}"
              - name: linuxhq-b-00
                az: us-east-1b
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,4) }}"
              - name: linuxhq-b-01
                az: us-east-1b
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,5) }}"
              - name: linuxhq-b-02
                az: us-east-1b
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,6) }}"
              - name: linuxhq-b-03
                az: us-east-1b
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,7) }}"
              - name: linuxhq-c-00
                az: us-east-1c
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,8) }}"
              - name: linuxhq-c-01
                az: us-east-1c
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,9) }}"
              - name: linuxhq-c-02
                az: us-east-1c
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,10) }}"
              - name: linuxhq-c-03
                az: us-east-1c
                cidr: "{{ '10.0.0.0/16' | ansible.utils.ipsubnet(24,11) }}"

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
