---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: iam_user
      tags:
        - molecule-idempotence-notest

    - role: iam_group
      iam_group_list: []
      tags:
        - molecule-idempotence-notest

    - iam_group
...
