---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        iam_group_list:
          "{{ iam_group_list |
              map('combine', {'state': 'absent'}) }}"
        iam_user_list:
          "{{ iam_group_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - iam_group
    - iam_user
...
