---
dependencies:
  - role: ec2_ami_info
    tags: ec2_instance
  - role: ec2_vpc_subnet_info
    tags: ec2_instance
galaxy_info:
  role_name: ec2_instance
  author: Taylor Kimball
  description: Manage aws ec2 instances
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - ec2
    - instance
...
