---
- name: Ensure ec2 elastic ip addresses are associated
  tags:
    - ec2_eip
  amazon.aws.ec2_eip:
    allow_reassociation: "{{ _eip.allow_reassociation | d(false) }}"
    device_id: "{{ _eip.device_id }}"
    in_vpc: "{{ _eip.in_vpc | d(false) }}"
    public_ip: "{{ __ec2_eip_dict[_eip.name].public_ip }}"
    purge_tags: "{{ _eip.purge_tags | d(true) }}"
    release_on_disassociation: "{{ _eip.release_on_disassociation | d(false) }}"
    reuse_existing_ip_allowed: "{{ _eip.reuse_existing_ip_allowed | d(false) }}"
    state: present
    tags:
      "{{ _eip.tags |
          d({}) |
          combine({'Name': _eip.name}) }}"
    validate_certs: true
  register: __ec2_eip_result_associate
  loop: "{{ __ec2_eip_list }}"
  loop_control:
    label: "{{ _eip.name | d(none) }}"
    loop_var: _eip
  when:
    - _eip.name is defined
    - _eip.name in __ec2_eip_dict.keys()
    - _eip.device_id is defined
    - _eip.state is not defined or
      _eip.state == 'present'
    - __ec2_eip_dict[_eip.name].public_ip is defined
  changed_when: false
  async: "{{ ansible_check_mode | ternary(0, ec2_eip_async) }}"
  poll: "{{ ec2_eip_poll }}"

- name: Ensure associated ec2 elastic ip address jobs are complete
  tags:
    - ec2_eip
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __ec2_eip_status_associate
  loop: "{{ __ec2_eip_result_associate.results }}"
  loop_control:
    label: "{{ _jid._eip.name | d(none) }}"
    loop_var: _jid
  when:
    - _jid.ansible_job_id is defined
  until:
    - __ec2_eip_status_associate.finished | bool
  retries: "{{ ec2_eip_retries }}"
  delay: "{{ ec2_eip_delay }}"
...
