---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: ec2_vpc_dhcp_option
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - ec2_vpc_dhcp_option_info
...
