---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_ami_info
    - ec2_instance_info
    - ec2_vol_info
    - ec2_vpc_net_info
    - ec2_vpc_subnet_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _ec2_vol_info_dict['linuxhq-vol-a-01'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-a-02'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-a-03'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-a-04'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-a-05'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-a-06'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-b-01'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-b-02'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-b-03'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-b-04'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-b-05'].id is defined
          - _ec2_vol_info_dict['linuxhq-vol-b-06'].id is defined

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ec2_vol_list:
          - instance: none
            volumes:
              "{{ ec2_vol_list.0.volumes |
                  map('combine', {'state': 'absent'}) +
                  ec2_vol_list.1.volumes |
                  map('combine', {'state': 'absent'}) }}"
        ec2_instance_list:
          "{{ ec2_instance_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_subnet_list:
          "{{ ec2_vpc_subnet_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_vol
        - ec2_instance
        - ec2_vpc_subnet
        - ec2_vpc_net
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
