---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: ec2_transit_gateway
      tags:
        - molecule-idempotence-notest

    - ec2_transit_gateway_info
...
