---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_transit_gateway_info

  post_tasks:
    - name: Ensure info is verified
      tags:
        - ec2_transit_gateway_info
      ansible.builtin.assert:
        that:
          - _ec2_transit_gateway_info_dict['linuxhq-00'].transit_gateway_id is defined
          - _ec2_transit_gateway_info_dict['linuxhq-01'].transit_gateway_id is defined
          - _ec2_transit_gateway_info_dict['linuxhq-02'].transit_gateway_id is defined
          - _ec2_transit_gateway_info_dict['linuxhq-03'].transit_gateway_id is defined
          - _ec2_transit_gateway_info_dict['linuxhq-04'].transit_gateway_id is defined

    - name: Ensure inventory lists are formatted
      tags:
        - ec2_transit_gateway_info
      ansible.builtin.set_fact:
        ec2_transit_gateway_list:
          "{{ ec2_transit_gateway_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      tags:
        - ec2_transit_gateway_info
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_transit_gateway
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
