---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: ec2_vpc_net
      tags:
        - molecule-idempotence-notest

    - role: ec2_vpc_igw
      tags:
        - molecule-idempotence-notest

    - role: ec2_vpc_subnet
      tags:
        - molecule-idempotence-notest

    - role: ec2_vpc_nat_gateway
      tags:
        - molecule-idempotence-notest

    - ec2_vpc_nat_gateway_info
...
