---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: iam_managed_policy
      iam_managed_policy_list: []
      tags:
        - molecule-idempotence-notest

    - iam_managed_policy
...
