---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    - name: Ensure inventory lists are formatted
      tags:
        - iam_managed_policy
      ansible.builtin.set_fact:
        iam_managed_policy_list:
          "{{ iam_managed_policy_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - iam_managed_policy
...
