---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: ec2_vpc_net
      tags:
        - molecule-idempotence-notest

    - role: ec2_vpc_igw
      ec2_vpc_igw_list: []
      tags:
        - molecule-idempotence-notest

    - ec2_vpc_igw
...
