---
dependencies: []
galaxy_info:
  role_name: service_quota
  author: Taylor Kimball
  description: Manage aws service quotas
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - quota
    - service
...
