---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: ec2_placement_group
      ec2_placement_group_list: []
      tags:
        - molecule-idempotence-notest

    - ec2_placement_group
...
