---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_vpc_net_info
    - ec2_vpc_subnet_info

  post_tasks:
    - name: Ensure ec2 vpc subnet info is verified
      tags:
        - ec2_vpc_subnet_info
      ansible.builtin.assert:
        that:
          - _ec2_vpc_subnet_info_dict['linuxhq-a-00'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-a-01'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-a-02'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-a-03'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-b-00'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-b-01'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-b-02'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-b-03'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-c-00'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-c-01'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-c-02'].id is defined
          - _ec2_vpc_subnet_info_dict['linuxhq-c-03'].id is defined

    - name: Ensure inventory lists are formatted
      tags:
        - ec2_vpc_subnet_info
      ansible.builtin.set_fact:
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_subnet_list:
          "{{ ec2_vpc_subnet_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      tags:
        - ec2_vpc_subnet_info
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_vpc_subnet
        - ec2_vpc_net
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
