---
dependencies: []
galaxy_info:
  role_name: ec2_ami_info
  author: Taylor Kimball
  description: Gather information about ec2 amazon machine images
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - ami
    - aws
    - ec2
    - info
...
