---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: iam_user
      iam_user_list: []
      tags:
        - molecule-idempotence-notest

    - iam_user
...
