---
allow_duplicates: true
dependencies: []
galaxy_info:
  role_name: route53_resolver_info
  author: Taylor Kimball
  description: Gather information about route53 resolvers
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - info
    - resolver
    - route53
...
