---
ec2_instance_metadata_async: 300
ec2_instance_metadata_batch: 10
ec2_instance_metadata_delay: 3
ec2_instance_metadata_http_endpoint: enabled
ec2_instance_metadata_http_tokens: required
ec2_instance_metadata_http_put_response_hop_limit: 2
ec2_instance_metadata_instance_metadata_tags: disabled
ec2_instance_metadata_poll: 0
ec2_instance_metadata_regions:
  - us-east-1
ec2_instance_metadata_retries: 100
...
