---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_vpc_net_info
    - ec2_vpc_subnet_info
    - efs_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _efs_info_dict['linuxhq-efs1'].encrypted | bool
          - _efs_info_dict['linuxhq-efs1'].mount_point is defined
          - _efs_info_dict['linuxhq-efs1'].mount_targets | length == 3
          - _efs_info_dict['linuxhq-efs1'].performance_mode == 'generalPurpose'
          - _efs_info_dict['linuxhq-efs2'].encrypted | bool
          - _efs_info_dict['linuxhq-efs2'].mount_point is defined
          - _efs_info_dict['linuxhq-efs2'].mount_targets | length == 3
          - _efs_info_dict['linuxhq-efs2'].performance_mode == 'generalPurpose'

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_subnet_list:
          "{{ ec2_vpc_subnet_list |
              map('combine', {'state': 'absent'}) }}"
        efs_list:
          "{{ efs_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - efs
        - ec2_vpc_subnet
        - ec2_vpc_net
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
