---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - ec2_transit_gateway_info
    - ec2_transit_gateway_vpc_attachment_info
    - ec2_vpc_net_info
    - ec2_vpc_subnet_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _ec2_transit_gateway_vpc_attachment_info_dict['linuxhq'].state == 'available'
          - _ec2_transit_gateway_vpc_attachment_info_dict['linuxhq'].subnet_ids.0 ==
              ec2_transit_gateway_vpc_attachment_list.0.subnets.0
          - _ec2_transit_gateway_vpc_attachment_info_dict['linuxhq'].transit_gateway_attachment_id is defined
          - _ec2_transit_gateway_vpc_attachment_info_dict['linuxhq'].transit_gateway_id ==
              ec2_transit_gateway_vpc_attachment_list.0.transit_gateway
          - _ec2_transit_gateway_vpc_attachment_info_dict['linuxhq'].vpc_id ==
              ec2_vpc_subnet_list.0.vpc_id

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ec2_transit_gateway_list:
          "{{ ec2_transit_gateway_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_transit_gateway_vpc_attachment_list:
          "{{ ec2_transit_gateway_vpc_attachment_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_subnet_list:
          "{{ ec2_vpc_subnet_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - ec2_transit_gateway_vpc_attachment
        - ec2_transit_gateway
        - ec2_vpc_subnet
        - ec2_vpc_net
      loop_control:
        label: "{{ _role }}"
        loop_var: _role

...
